name: "Terraform Plan"

on: push

jobs:
  discovery-changes:
    name: "discovery-changes"
    runs-on: ubuntu-latest
    outputs:
      folder_changes: ${{ steps.folder_json.outputs.folder_changes }}
    steps:
      - name: print folder changes
        id: folder_json
        run: echo "::set-output name=folder_changes::{\"folders\":[\"teste\", \"exemplo\"]}"
        
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    needs: discovery-changes
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.discovery-changes.outputs.folder_changes)}}
    steps:
      - name: debug
        run: echo $RESOURCE
        env:
          RESOURCES: ${{ matrix.folders }} 
